version: '3.8'

services:
  api-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: m3zold-server-debug
    ports:
      - "8081:8080"
      - "2345:2345"
    depends_on:
      - db
    environment:
      - DB_URL=postgres://m3zold-server:m3zold-server@db:5432/m3zold-server
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: m3zold-server
      POSTGRES_USER: m3zold-server
      POSTGRES_PASSWORD: m3zold-server
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
