services:
  api-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: m3zold-server-debug
    ports:
      - "8081:8080"
      - "3333:2345"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_URL=postgres://m3zold-server:m3zold-server@db:5432/m3zold-server
    volumes:
      - .:/app
    working_dir: /app
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: m3zold-server
      POSTGRES_USER: m3zold-server
      POSTGRES_PASSWORD: m3zold-server
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U m3zold-server -d m3zold-server" ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  pgdata:
