name: Deploy m3zold server API

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Pull latest code on VPS
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 83.166.247.181
        username: root
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /root/m3zold-server
          git pull origin main

    - name: Restart Docker Compose
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 83.166.247.181
        username: root
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /root/m3zold-server
          docker-compose down
          docker-compose up -d --build

    - name: Healthcheck
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 83.166.247.181
        username: root
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          curl -f http://localhost:8080/auth/check || exit 1
