name: Deploy Go LAEG API

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Upload project to VPS
      uses: appleboy/scp-action@v0.1.4
      with:
        host: 83.166.247.181
        username: root
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "."
        target: "/root/go-laeg"

    - name: Restart Docker Compose
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 83.166.247.181
        username: root
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /root/go-laeg
          docker-compose down
          docker-compose up -d --build

